SELECT * FROM PAYMENT INNER JOIN PAYMENTTYPE ON PAYMENT.TYPE_ID=PAYMENTTYPE.ID WHERE PAYMENTTYPE.NAME='MONTHLY';
SELECT * FROM MARK INNER JOIN SUBJECT ON MARK.SUBJECT_ID=SUBJECT.ID WHERE SUBJECT.NAME='Art';
SELECT * FROM STUDENT INNER JOIN PAYMENTTYPE ON STUDENT.PAYMENT_TYPE_ID=PAYMENTTYPE.ID WHERE PAYMENTTYPE.NAME='WEEKLY';
SELECT * FROM STUDENT INNER JOIN MARK ON STUDENT.ID=MARK.STUDENT_ID INNER JOIN SUBJECT ON MARK.SUBJECT_ID=SUBJECT.ID WHERE SUBJECT.NAME='Math';
