SELECT * FROM MARK WHERE MARK>6 ORDER BY MARK DESC;
SELECT * FROM PAYMENT WHERE PAYMENT<300 ORDER BY PAYMENT ASC;
SELECT * FROM PAYMENTTYPE ORDER BY NAME ASC;
SELECT * FROM STUDENT WHERE ORDER BY NAME DESC;
SELECT student.* from student inner join payment on payment.student_id = student.id where payment.amount > 1000 GROUP BY student.birthday ASC;