SELECT * FROM PAYMENT WHERE AMOUNT>=500;
SELECT * FROM student WHERE TIMESTAMPDIFF(YEAR, birthday, CURDATE()) > 20;
SELECT * FROM student WHERE groupnumber = 10 AND TIMESTAMPDIFF(YEAR, birthday, CURDATE()) < 20;
SELECT * FROM STUDENT WHERE NAME='Mike' OR groupnumber IN (4,5,6);
SELECT * FROM payment WHERE payment_date >= NOW() - INTERVAL 8 MONTH;
SELECT * FROM STUDENT WHERE NAME LIKE 'A%';
SELECT * FROM STUDENT WHERE (NAME='Roxi' AND GROUPNUMBER=4) OR (NAME='Tallie' AND GROUPNUMBER=9);



