ALTER TABLE STUDENT MODIFY BIRTHDAY DATE NOT NULL;
ALTER TABLE MARK MODIFY MARK NOT NULL CHECK(MARK BETWEEN 1 AND 10), MODIFY STUDENT_ID INT NOT NULL, MODIFY SUBJECT_ID INT NOT NULL;
ALTER TABLE SUBJECT MODIFY GRADE INT NOT NULL CHECK(GRADE BETWEEN 1 AND 5);
ALTER TABLE PAYMENTTPE MODIFY NAME VARCHAR(255) UNIQUE;
ALTER TABLE PAYMENT MODIFY TYPE_ID BIGINT NOT NULL, MODIFY STUDENT_ID INT NOT NULL, MODIFY AMOUNT DECIMAL(10, 2) NOT NULL, MODIFY payment_date TIMESTAMP NOT NULL;