SELECT max(student.birthday) from student;
SELECT MIN(PAYMENT.PAYMENT_DATE) FROM PAYMENT;
SELECT AVG(MARK.MARK) FROM MARK JOIN SUBJECT ON SUBJECT.ID = MARK.SUBJECT_ID WHERE SUBJECT.NAME LIKE 'Math%';
SELECT MIN (PAYMENT.AMOUNT) FROM PAYMENT JOIN PAYMENTTYPE ON PAYMENT.TYPE_ID=PAYMENTTYPE.ID WHERE PAYMENTTYPE.NAME LIKE 'WEEKLY%';
