    CREATE TABLE Student(
        ID BIGINT PRIMARY KEY,
        NAME VARCHAR(255),
        BIRTHDATE DATE,
        GROUP INT
    );
    CREATE TABLE Subject(
        ID BIGINT PRIMARY KEY NOT NULL,
        NAME VARCHAR(255),
        DESCRIPTION VARCHAR(255),
        GRADE INT NOT NULL
    );
    CREATE TABLE PaymentType(
        ID BIGINT PRIMARY KEY NOT NULL,
        NAME VARCHAR(255)
    );
    CREATE TABLE Payment(
        ID BIGINT PRIMARY KEY NOT NULL,
        TYPE_ID BIGINT NOT NULL,
        AMOUNT DECIMAL(10,2) NOT NULL,
        STUDENT_ID BIGINT NOT NULL,
        PAYMENT_DATE DATETIME,
        CONSTRAINT FK_PAYMENT_TYPE FOREIGN KEY(TYPE_ID) REFERENCES PaymentType(ID),
        CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES Student(ID)
    );
    CREATE TABLE Mark(
        ID BIGINT PRIMARY KEY NOT NULL,
        STUDENT_ID BIGINT NOT NULL,
        SUBJECT_ID BIGINT NOT NULL,
        MARK INT NOT NULL,
        CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES Student(ID),
        CONSTRAINT FK_SUBJECT_ID FOREIGN KEY (SUBJECT_ID) REFERENCES Subject(ID)
    );



