SELECT * FROM STUDENT HAVING AVG(MARK) > 8;
SELECT ID, NAME FROM STUDENT INNER JOIN MARK ON STUDENT.ID=MARK.STUDENT_ID HAVING MIN(MARK.MARK)>7;
SELECT ID, NAME FROM STUDENT INNER JOIN PAYMENT ON STUDENT.ID=PAYMENT.STUDENT_ID HAVING COUNT(PAYMENT.STUDENT_ID)>2 AND YEAR(PAYMENT.DATE)=2019;